name: ad_hoc_ident_util_flutter
description: "Provides Flutter specific utility functionalities as part of the ad_hoc_ident framework."
version: 0.0.1-preview-1
homepage: https://github.com/FabianMoeckel/ad_hoc_ident_util_flutter
repository: https://github.com/FabianMoeckel/ad_hoc_ident_util_flutter

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ad_hoc_ident: ^0.0.1-preview-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
